### ISSUE TITLE
After playing a card, cards need to be resorted

### ISSUE THREAD

**Issue by logan-hendricks** [jak103/uno#175]
Currently, how we sort cards is entirely done on the frontend.  It would be preferable to have the frontend report to the backend how the player would like to have their cards sorted... as such the backend can sort the data before presenting the data to the frontend.

**Comment by hhenrichsen** [comment]
I think this would simplify calls if we just re-sorted it the selected way on the frontend after each call, unless I'm missing something.

**Comment by logan-hendricks** [comment]
@hhenrichsen It actually does this currently. but what it does is the following:

- Gets the game state
- Calls to re-sort the cards
- The card render in server side order
- The cards then re-render in the sorted order on the frontend.

It feels a little janky as it currently operates.

Ideally it would sort the cards before ever rendering to the screen. I didn't check `exactly` when the re-sort is called. but it does cause the cards to render twice after each time you draw a card. I'm not sure if it could just be called sooner, or if it is computationally expensive of a transaction for the frontend that it just takes a second to be accomplished.

**Comment by Eric4Bell** [comment]
@logan-hendricks 

I solved this by sorting after each call that updates the player's hand, like @hhenrichsen described. The problem was that it was only sorting when updated data was being sent from the server, not when the client sent the data. That's why you were seeing the cards get unsorted when playing a card, but then sorted again on the next update sent by the backend.
