### ISSUE TITLE
Production build is broken

### ISSUE THREAD

**Issue by idiomic** [jak103/uno#73]
Running "docker build ." on the top level results in docker failing mid-way through. It seems that the production build is dependent upon many development environment packages including the build-watch and linters.

I've been working on a github action to deploy to ECS but I've been stuck trying to figure out this dependency issue for hours now.

**Comment by TylerRHoyer** [comment]
The development dependencies has many packages required for the vue-cli-service to build the deployment. Because this is so, setting NODE_ENV to "production" causes many of these packages to not be included and the build to fail. In addition, the global installs for the @vue/cli-service-global and @vue/cli packages are not being done in the top level directory as in the client directory. Adding the global installs and using a development build resolves the issues for me. What is the proper way to solve this issue?
