### ISSUE TITLE
Not open to public contributions

### ISSUE THREAD

**Issue by logan-hendricks** [jak103/uno#9]
So, I would love to put in a PR to fix the volume mapping, but this Repo is not open for public contributions.

Would you like me to create a fork? Or are you planning on adding all of the class as contributors?

**Comment by jak103** [comment]
Logan,

Good question. I have one issue that has prevented me from moving forward.
In order to use the Google Firestore nosql database, you have to have a
credentials file. If I version this file, then anyone who sees the file can
get access to the database, which is not good. I've been thinking about
making the repository private so I can safely version the cert file, but I
lose a bunch of cool github features when I do that. I think I'm going to
make a separate private repository and submodule it to the
public repository. If that is the case, then I'll probably have everyone as
contributors on the uno repository.

What are your thoughts?

Thanks,

Jacob

**Comment by logan-hendricks** [comment]
Jacob,

hmmm....... Would everyone in the class need access to that private repository for local development? Or is only used on a production deploy?

**Comment by jak103** [comment]
Unfortunately for local development. I can look into that more and figure
something out. Maybe we have a different nosql db for local development and
an abstraction layer to the code doesn't know when it changes between dbs.

Options exist.

**Comment by logan-hendricks** [comment]
Gotcha, that makes sense.

To clarify my thoughts then.

1. I also think creating the abstraction layer  on the database makes sense :) 
2. I think adding a private repository as a submodule makes sense to me overall.
3. It sounds like this is NOT the case, but if we are in a scenario where the entire class would needed to be added to the private sub-module repository, my counter thought would be.... could we just make **this** repository private? or delete/recreate this repository and make it private? I suppose I approach it from the thought of  "does this just bubbling up the concern".
4. Most of the time that I've faced these problems at work, we've typically established a `secrets management` process, through one of the following:
    - A secrets mangaement tool (vault, AWS secrets manager, etc)
    - A private, yet shared file store (mounted directory, nexus, S3 Bucket)
    - A secure way of distribution....... (USB, encrypted emails, git submodules) 
    - Managed entirely on the build/deploy process (jenkins, chef, salt, etc...)

The major problem with all of these solutions... is that short of sending an `encrypted email`.... it basically just bubbles up a credential issue. You have to pass someone credentials in order for them to get access to credentials....

So in your case, I think the most lightweight solutions are to either make the private git submodule... or to just make this repository private and store it here. I would lean towards the git submodule, as it could be entirely managed by the deployment/build process (Jenkins, Google Cloud Build), and you could limit access to the submodule.

**Comment by jak103** [comment]
We are going to go ahead and add everyone as collaborators. This should work.
